### ISSUE TITLE
Attribute error in MCSamples.getParams

### ISSUE THREAD

**Issue by misharash** [cmbant/getdist#56]
Hello.
I tried to `loadMCSamples` from Cobaya which contained variables named "chi2__H0" and "chi2__H0.riess201903".
I got an error `numpy.ndarray has no attribute riess201903` when I called `getParams`. The code tried to set `riess201903` attribute to `chi2__H0` which was already an array and failed.
I wonder if it may be more convenient to use a dictionary to get parameters by names instead of this attribute business.

**Comment by cmbant** [comment]
Please could you attach chains to reproduce - thanks.

**Comment by misharash** [comment]
[planckH3LCDM.zip](https://github.com/cmbant/getdist/files/5648952/planckH3LCDM.zip)
When I run the following in the same directory as the two files in archive, the issue is reproduced:
```
from getdist.mcsamples import loadMCSamples
samples = loadMCSamples('./planckH3LCDM')
pars = samples.getParams()
```

**Comment by misharash** [comment]
I've found quite a simple workaround with dictionary:
```
def getParamsDict(samples):
    obj = dict()
    for i, name in enumerate(samples.paramNames.names):
        obj[name.name] = samples.samples[:, i]
    return obj
```

**Comment by cmbant** [comment]
cf https://github.com/CobayaSampler/cobaya/issues/125#issuecomment-739519733

**Comment by cmbant** [comment]
It's a tricky one that, arising because you have both params.H0 and params.H0.riess201903. getParams() creates an object with attribute H0, where H0 has attribute riess201903. But since you have H0 as well, that is set to an ndarray, which does not allow you to add attributes without subclassing.

Try https://github.com/cmbant/getdist/commit/9445bc0b571e942a426792f23d01b237b4fba81a, which instead makes H0.value for the aggregate variable.
