### ISSUE TITLE
Does getdist support emcee?

### ISSUE THREAD

**Issue by yuanzunli** [cmbant/getdist#60]
@cmbant  Dear Antony,  I find getdist is a very useful for analyzing MCMC chains. Since getdist is written in Python, I'm wondering whether it supports MCMC programmer of Python such as emcee (https://emcee.readthedocs.io/en/stable/) ? emcee is so popular that if getdist  is compatible with it, it would be great.

**Comment by cmbant** [comment]
I don't know if emcee specifically supports getdist text chain format, but you can use GetDist to load samples from standard numpy arrays (e.g. the first examples in https://getdist.readthedocs.io/en/latest/plot_gallery.html), which shouldn't be difficult.

For file input support, you'd have to raise an issue with emcee for them to export it. I'm not sure they currently support propagating parameter names, limits and labels consistently like cosmomc and Cobaya.

You/they could also consider making a [Cobaya](https://github.com/CobayaSampler/cobaya) wrapper for emcee so that it can be used directly with that as well as the standard sampler and polychord, saving results in Cobaya's supported format directly.
